### ISSUE TITLE
Fabric: some options look broken

### ISSUE THREAD

**Issue by MeeniMc** [noobanidus/Lootr#146]
## Versions

- lootr 0.4.22.61 
- cloth-config 8.2.88 
- modmenu 4.0.6 
- fabric-api 0.64.0+1.19.2
- minecraft 1.19.2 

## Issues

Some options do not look right (translation string is missing). Unsure if toggling the options has an effect or not. 
Some matching errors appear in the log when interacting with the config screen. 

### Visual

![image](https://user-images.githubusercontent.com/68366846/197014054-b7c6fb8d-2582-424d-a58c-128b384901f7.png)

### Log

```
[13:08:19] [Render thread/ERROR]: No GUI provider registered for field 'private static java.util.Set net.zestyblaze.lootr.config.LootrModConfig.DECAY_MODS'!
[13:08:19] [Render thread/ERROR]: No GUI provider registered for field 'private static java.util.Set net.zestyblaze.lootr.config.LootrModConfig.DECAY_TABLES'! 
[13:08:19] [Render thread/ERROR]: No GUI provider registered for field 'private static java.util.Set net.zestyblaze.lootr.config.LootrModConfig.REFRESH_MODS'! 
[13:08:19] [Render thread/ERROR]: No GUI provider registered for field 'private static java.util.Set net.zestyblaze.lootr.config.LootrModConfig.REFRESH_TABLES'! 
[13:08:19] [Render thread/ERROR]: No GUI provider registered for field 'private static java.util.Set net.zestyblaze.lootr.config.LootrModConfig.DIM_WHITELIST'!
[13:08:19] [Render thread/ERROR]: No GUI provider registered for field 'private static java.util.Set net.zestyblaze.lootr.config.LootrModConfig.DIM_BLACKLIST'! 
[13:08:19] [Render thread/ERROR]: No GUI provider registered for field 'private static java.util.Set net.zestyblaze.lootr.config.LootrModConfig.DECAY_DIMS'! 
[13:08:19] [Render thread/ERROR]: No GUI provider registered for field 'private static java.util.Set net.zestyblaze.lootr.config.LootrModConfig.REFRESH_DIMS'! 
[13:08:19] [Render thread/ERROR]: No GUI provider registered for field 'private static java.util.Set net.zestyblaze.lootr.config.LootrModConfig.LOOT_BLACKLIST'!
[13:08:19] [Render thread/ERROR]: No GUI provider registered for field 'private static java.util.Map net.zestyblaze.lootr.config.LootrModConfig.replacements'!
[13:08:19] [Render thread/ERROR]: No GUI provider registered for field 'private static java.util.Set net.zestyblaze.lootr.config.LootrModConfig.LOOT_MODIDS'!
```

**Comment by MeeniMc** [comment]
Thanks for updating to 1.19.3, this defect is still present in 0.4.25.65.

**Comment by ZestyBlaze** [comment]
Hm this might be a cloth config issue, I've been meaning to update the config anyway so I'll mark that for the next update

**Comment by noobanidus** [comment]
@ZestyBlaze Was this completed?

**Comment by ZestyBlaze** [comment]
I think I did it but forgot to commit. I'm currently in the middle of a healthcare emergency so I'll have to commit it later when I get back from the hospital

**Comment by noobanidus** [comment]
No pressure! Take care of yourself.

**Comment by ZestyBlaze** [comment]
Latest push should fix this, just need nooby to compile it

**Comment by MeeniMc** [comment]
The config screen texts are now correct, however the log warnings are still present. Not sure if they indicate a real problem or are just noise.

**Comment by noobanidus** [comment]
I'll try to look into this some time this week.

**Comment by noobanidus** [comment]
The log warnings would seem to be irrelevant as these are internal values that don't require a configuration element. I'll look into adding an ignore line to these.
