### ISSUE TITLE
latest 1.20.1 fabric file is a 1.19 mod

### ISSUE THREAD

**Issue by szunakabeats** [noobanidus/Lootr#293]
![image](https://github.com/LootrMinecraft/Lootr/assets/88375166/7593ed4e-f14f-4b50-b7f3-63816ca0247d)

**Comment by noobanidus** [comment]
I knew I forgot something!

**Comment by noobanidus** [comment]
Ah, yeah, it was tagged as 1.20 when it was the 1.19 release. Fixed!

**Comment by szunakabeats** [comment]
sry its still showing up ..

![image](https://github.com/LootrMinecraft/Lootr/assets/88375166/fe21380a-5bc3-441b-8ceb-305136d21a54)

**Comment by noobanidus** [comment]
Unfortunately that's a bug with CurseForge and not something I can do anything about. It's fixed in CurseForge's database online, it's just cached in your system for some reason (or in the app).

![](https://i.imgur.com/iTfCdx3.png)

**Comment by szunakabeats** [comment]
Ahhh okay I see… maybe when the next app update comes out, then it will be fixed.

thx for looking into it

**Comment by szunakabeats** [comment]
hm are u sure tho ? it still shows up even online when i filter it by loader and game version

![image](https://github.com/LootrMinecraft/Lootr/assets/88375166/77e6351c-27be-40c1-a2a9-03be2a0a45e6)

**Comment by noobanidus** [comment]
![](https://i.imgur.com/5fvNTG1.png)

That would be an issue for CurseForge, it isn't flagged for 1.20 ...

**Comment by purejosh** [comment]
That's weird. Curseforge be doing some dumb here.

**Comment by noobanidus** [comment]
I've reopened this issue as it's been reported by others also. I've asked CurseForge to look into it and will update when I hear back from them.

**Comment by noobanidus** [comment]
I haven't heard anything from CurseForge on this issue, so I've bumped the current version of the 1.19.0 version of Fabric and posted a new release. Once that release is live, I'll be archiving this release.

Sorry for all the confusion this has been causing.

**Comment by szunakabeats** [comment]
thx for your work ! :)
