### ISSUE TITLE
Forge 1.20.1 Lootr no working in world_the_end

### ISSUE THREAD

**Issue by kitovoi111** [noobanidus/Lootr#593]
Players complain that there are no chests at all in world_the_end lootr.

**Comment by kitovoi111** [comment]
lootr-forge-1.20-0.7.35.90.jar

**Comment by kitovoi111** [comment]
![Image](https://github.com/user-attachments/assets/d3bf1b21-a993-4722-83e5-61fc7b459f3a)

**Comment by noobanidus** [comment]
This looks as though it could be related to quark: https://github.com/VazkiiMods/Quark/issues/5136

**Comment by kitovoi111** [comment]
![Image](https://github.com/user-attachments/assets/7d301a0d-aded-4c94-91c6-86fb1c19bcbb)
Hmmm

**Comment by kitovoi111** [comment]
[lootr-common.txt](https://github.com/user-attachments/files/18913950/lootr-common.txt)

**Comment by kitovoi111** [comment]
I disabled Quark chests in world generation in quark-common.toml but for some reason Artifacts mod sometimes generates Quark chests and some structures without lootr

**Comment by kitovoi111** [comment]
fixed.

**Comment by kitovoi111** [comment]
![Image](https://github.com/user-attachments/assets/1deac538-a05f-45a3-8c52-cb3671d64892)

Alex's Caves, who lootr???

**Comment by ambientNexus** [comment]
Issue is still occuring with latest versions of quark and lootr, it hasn't been fixed.

**Comment by noobanidus** [comment]
If you disable Quark's conversion, Lootr should take over. The rest of the issue is on Quark's side.
